FROM nginx

MAINTAINER Glenn Dayton

#VOLUME /root/budget-tracker/ng2/dist:/usr/local/nginx/html
VOLUME /Users/gdayton/Documents/budget-tracker/ng2/dist:/usr/local/nginx/html

#RUN npm install

EXPOSE 80
